anchor_version = "0.29"

[features]
seeds = false

[programs.localnet]
amm_v3 = "CAMMCzo5YL8w4VFF8KVHrK22GGUsp5VTaW7grrKgrWqK"

[registry]
url = "https://github.com/swap-dot-io/swap-io-clmm"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"
