services:
  anchor_build:
    image: backpackapp/build:v0.29.0
    container_name: anchor_build
    env_file:
      - .secrets/.env
    environment:
      - CARGO_TARGET_DIR=/workdir/docker-target
      - PATH=/root/.local/share/solana/install/active_release/bin:/root/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    volumes:
      - ./:/workdir
      - ./.secrets/deployer.json:/.keys/deployer.json
      - ./.secrets/admin.json:/.keys/admin.json
      - ./.secrets/fund_owner.json:/.keys/fund_owner.json
      - ./.secrets/program.json:/.keys/program.json
    working_dir: /workdir
    command: bash
    #tty: true
    #stdin_open: true
